name: neurobooster
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.25.2
  - numpy-base=1.25.2
  - scikit-learn
  - pandas
  - tqdm
  - pillow
  - matplotlib
  - scipy
  - nibabel
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - timm==0.4.9
      - medmnist==3.0.2
      - torchio==0.19.2
